export const GOAL_TITLE_CHANGE = "GOAL_TITLE_CHANGE";
export const GOAL_DESCRIPTION_CHANGE = "GOAL_DESCRIPTION_CHANGE";
export const GOAL_LIST_ADD_ITEM = "GOAL_LIST_ADD_ITEM";
export const GOAL_LIST_COMPLETE_ITEM = "GOAL_LIST_COMPLETE_ITEM";
export const GOAL_LIST_DELETE_ITEM = "GOAL_LIST_DELETE_ITEM";
